export const FETCHING_USER = 'FETCHING_USER'
export const SINGLE_SMURF_SUCCESS = 'SINGLE_SMURF_SUCCESS'
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED'
export const SMURF_ADDED_SUCCESS = 'SMURF_ADDED_SUCCESS'

// Images CDN
export const FETCHING_IMAGE = 'FETCHING_IMAGE'
export const IMAGE_UPLOADED = 'IMAGE_UPLOADED'
export const IMAGE_UPDATED = 'IMAGE_UPDATED'
export const IMAGE_DELETED = 'IMAGE_DELETED'
export const IMAGE_UPLOADING = 'IMAGE_UPLOADING'
