export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL'
export const POST_SMURF_START = 'POST_SMURF_START'
export const POST_SMURF = 'POST_SMURF'
export const POST_SMURF_FAIL = 'POST_SMURF_FAIL'