export const FETCH_DATA_START = "FETCH_DATA_START"; 
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS"; 
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR"; 
export const ADD_SMURF_SUCCESS = "ADD_SMURF_SUCCESS"; 
export const ADD_SMURF_ERROR = "ADD_SMURF_ERROR"; 